#!/usr/bin/perl

# in my test server, the source pool is the four drives in the middle hotswap cage
# and the target pool is the four drives in the right-most hotswap cage.

my @sourcedisks;
push @sourcedisks, "/dev/disk/by-id/scsi-SATA_ST12000VN0007-2G_ZCH0BSCK";
push @sourcedisks, "/dev/disk/by-id/scsi-SATA_ST12000VN0007-2G_ZCH0BSFQ";
push @sourcedisks, "/dev/disk/by-id/scsi-SATA_ST12000VN0007-2G_ZCH0BSN1";
push @sourcedisks, "/dev/disk/by-id/scsi-SATA_ST12000VN0007-2G_ZCH0C0K9";

my @targetdisks;
push @targetdisks, "/dev/disk/by-id/scsi-SATA_ST12000VN0007-2G_ZCH0BSSK";
push @targetdisks, "/dev/disk/by-id/scsi-SATA_ST12000VN0007-2G_ZCH0BSTZ";
push @targetdisks, "/dev/disk/by-id/scsi-SATA_ST12000VN0007-2G_ZCH0BSFK";
push @targetdisks, "/dev/disk/by-id/scsi-SATA_ST12000VN0007-2G_ZCH0BSY0";

print "Validating disks and wiping labels... ";
my $sourcedisksstring;
my $targetdisksstring;
foreach my $disk (@sourcedisks) {
	if (! -e $disk) { print "WARNING: source $disk is not present in /dev/disk/by-id!\n"; exit 1; }
	system ("wipefs -qa $disk");
	$sourcedisksstring .= "$disk ";
}
foreach my $disk (@targetdisks) {
	if (! -e $disk) { print "WARNING: target $disk is not present in /dev/disk/by-id!\n"; exit 1; }
	system ("wipefs -qa $disk");
	$targetdisksstring .= "$disk ";
}
print "all disks are present in /dev/disk/by-id and clean.\n\n";

# create source and target arrays
my $btrfslevel = "raid1";
my $initcmd = "mkfs.btrfs -q -d $btrfslevel";
print "Creating arrays... ";
system("$initcmd -L source $sourcedisksstring");
system("$initcmd -L target $targetdisksstring");
print "source and target arrays created.\n\n";

# mount and display arrays
mkdir "/mnt/source";
mkdir "/mnt/target";
# compression is specified in the mount options for btrfs - enable or disable here
#system ("mount -o compress=lzo $sourcedisks[0] /mnt/source");
system ("mount $sourcedisks[0] /mnt/source");
system ("btrfs filesystem show /mnt/source");
#system ("mount -o compress=lzo $targetdisks[0] /mnt/target");
system ("mount $targetdisks[0] /mnt/target");
system ("btrfs filesystem show /mnt/target");

# create initial subvolume and snapshot on source
system ("btrfs subvolume create /mnt/source/fio");
system ("btrfs subvolume snapshot -r /mnt/source/fio /mnt/source/fio/snapshot_1");

# initial full replication to target (requires creating target first, on btrfs)
system ("btrfs subvolume create /mnt/target/fio");
system ("btrfs send /mnt/source/fio/snapshot_1 | btrfs receive /mnt/target/fio");
