#!/usr/bin/perl

my $source="source/fio";
my $target="target/fio";

my @sourcelist=`zfs list -Hrt snap -o name $source | sed 's/.*\@//'`;
my @targetlist=`zfs list -Hrt snap -o name $target | sed 's/.*\@//'`;

chomp @sourcelist;
chomp @targetlist;

# find most recent common snapshot
my $common='';
until ( ($common ne '') || (scalar @targetlist == 0) ) {
	my $targetsnap = pop @targetlist;
	my @matches = grep { /^$targetsnap$/ } @sourcelist;
	$common = $matches[0];
}

# find most recent snapshot on source
my $recent = pop @sourcelist;

if ($common eq $recent) {
	print "Target already contains most recent source snapshot $recent, nothing to do.\n";
	exit 0;
}

if ($common eq '') {
	print "Target and source do not have any matching snapshots, cannot replicate!\n";
	exit 1;
}

print "Replicating from $common to $recent...\n";
print "zfs send -I $source\@$common $source\@$recent | zfs receive $target \n";
system ("zfs send -I $source\@$common $source\@$recent | zfs receive $target");

